### ISSUE TITLE
Mystery issue in large (module-wise) workspaces with MTE tests

### ISSUE THREAD

**Issue by Cervator** [Terasology/ModuleTestingEnvironment#10]
Creating issue here to refer to https://github.com/MovingBlocks/Terasology/pull/3734 and https://github.com/Terasology/DynamicCities/pull/40 which cover it nicely. Thought at first it might be a repeat of #9 somehow (lots of class/package overlap between Cities and StaticCities) but it might be an engine issue in how classpaths are handled? I'm really not sure, but don't want to forget!

**Comment by keturn** [comment]
There have been enough module-and-classpath changes recently that I think we're several iterations beyond the linked PR, so I'll close this 2019-era issue.

As always, please do open a new one if you run in to something similar with the current version.
