### ISSUE TITLE
reducing the number of annotations

### ISSUE THREAD

**Issue by keturn** [Terasology/ModuleTestingEnvironment#76]
Setting up a test class currently looks like this:
```java
@Tag("MteTest")
@ExtendWith(MTEExtension.class)
@Dependencies("Pathfinding")
@UseWorldGenerator("Pathfinding:pathfinder")
public class PathfinderTest { /*…*/ }
```

Maybe we should make it look more like this:
```java
@ModuleEnvironmentTest(modules="Pathfinding", worldGenerator="Pathfinding:pathfinder")
public class PathfinderTest { /*…*/ }
```

- **Tag**: not required for MTE itself, but we do have a convention for adding it to all MTE-using tests for the benefit of separating the `unitTest` and `integrationTest` suites, so we might as well have something that applies it anywhere we're using MTE.
- **ExtendWith**: we do need one of these, but we can wrap it up in a [composed annotation](https://junit.org/junit5/docs/current/user-guide/#writing-tests-meta-annotations).
- **Dependencies** and **UseWorldGenerator**: MTE tests effectively _always_ need to provide a value for Dependencies. An interface that says “use `ExtendWith`” can't express that sort of required parameter, but if we have a composed annotation for setting up the test, we can put the parameters in the same place.
    UseWorldGenerator has a useful default, so we don't need to make it _required,_ but we can help discoverability by putting it in the same place.
    Neither of these annotations is at all useful on classes that _aren't_ MTEExtension-enabled test classes, so we don't lose anything by taking them out of the interface.

**Comment by DarkWeird** [comment]
I agree.
Composed annotation looks better.

**Comment by keturn** [comment]
I've been keeping this in mind as I've been adding parameters in MTE's [new home](https://github.com/MovingBlocks/Terasology/tree/develop/engine-tests/src/main/java/org/terasology/engine/integrationenvironment). I don't have the composed annotation set up yet, but I think we'll go that way.

Apparently GitHub's "transfer issue" function doesn't let me move things between @Terasology and @MovingBlocks, so I guess I'll close this here.
